### ISSUE TITLE
请问有没有优化访问速度的方案？

### ISSUE THREAD

**Issue by SivonLi** [Astrian/Nagging-backend#3]
大佬您好，我在v2看到您的这个项目感觉很棒，于是我就把项目按照readme中的步骤，部署到了heroku和netlify。
部署成功后我尝试在国内直连的情况下打开网站，发现获取不到数据。但我直连访问您的网站，并没有这个情况，甚至很快。
所以我想问问您的优化访问速度的方案是什么？

**Comment by SivonLi** [comment]
这是等待几分钟后，控制台返回的错误和警告。
![Snipaste_2021-08-19_10-25-51.png](https://i.loli.net/2021/08/19/ehM6vwEqN5AHaGo.png)

**Comment by Astrian** [comment]
I am not so sure，不过我猜可能和你用的是 heroku 默认域名有关，不排除是防火墙对 `*.herokuapp.com` 整体做了污染

**Comment by SivonLi** [comment]
好吧，谢谢大佬回复，可惜我没有信用卡没法在heroku中绑域名。不过我今天用cf给heroku设置了反向代理，直连可以访问了，但还是很慢，难搞。
